### ISSUE TITLE
Add the option to use KontentElementCodename instead of KontentElementId for MAPI model output

### ISSUE THREAD

**Issue by kentico-michaelb** [kontent-ai/model-generator-net#167]
### Motivation

In a multi-environment project, developers will want to upsert content type changes in non-production environments via the Management API, test the newly added elements, then run the same script against production (in the event they do not want to use, or cannot use, the environment swap feature -- which is the case for some projects that cannot engage in a long content freeze or have policies against sensitive content existing in downstream environments).  

The issue is that upserting these changes in content types in the different environments results in a different content type element ID for the elements, which means the developer cannot use the same models generated for the downstream (development environments) in the production environment. They need to re-run the model generator for production to ensure the _KontentElementId_ values as shown here: https://github.com/kontent-ai/model-generator-net#management-api-example-output  are valid.

### Proposed solution

If there was an option to use the codename instead of the internal ID, then you could run the generator against development, and re-use the outputs in other environments, rather than having to re-run the generator per environment.

### Additional context

This is in reference to a customer inquiry and I can bridge communication with them if necessary.

**Comment by Sevitas** [comment]
Hi, thanks for the issue, I will look into it.

**Comment by Simply007** [comment]
Please sync about the actual use case.

If decided to implement the feature - try to be consistent with JS as much as possible https://github.com/kontent-ai/model-generator-js#readme

**Comment by Sevitas** [comment]
Hi, we have introduced KontentElementId property in the [https://github.com/kontent-ai/model-generator-net/issues/112](https://github.com/kontent-ai/model-generator-net/issues/112) because it can be used while [working with variants language variants](https://github.com/kontent-ai/management-sdk-net#working-with-language-variants). Currently the codename is set to the `[JsonProperty("{codename}")]` attribute of the generated model.

### Proposed solution
1. include option for choosing desired identification option
a. Use string values separated by ';' so we are able to use multiple options. Do not use bool flag.
2. Generate model using specified options

```csharp
using System;
using Kentico.Kontent.Management.Models.Assets;
using Kentico.Kontent.Management.Models.Items;
using Kentico.Kontent.Management.Models.Items.Elements;
using Kentico.Kontent.Management.Modules.ModelBuilders;
using Newtonsoft.Json;

namespace KenticoKontentModels
{
    public partial class MyContentType
    {
        [JsonProperty("text")]
        [KontentElementId("77108990-3c30-5ffb-8dcd-8eb85fc52cb1")]
        [KontentElementCodename("text")]
        public TextElement Text { get; set; }
    }
}
```

3. Include codename in the https://github.com/kontent-ai/management-sdk-net/blob/a94d1601fc2baa7aa43b5dcffc1bf835085bf01a/Kontent.Ai.Management/Modules/Extensions/PropertyInfoExtensions.cs
4. Edit [working with variants language variants snippet](https://github.com/kontent-ai/management-sdk-net#working-with-language-variants)

What do you think about this @kentico-michaelb?

**Comment by kentico-michaelb** [comment]
I missed the part where JsonProperty is referring to the codename of the element, not the codename of the element data type (which is what I assumed from the names used in the README examples):

"JsonProperty's attribute value is being generated from element codename (not from the type) and KontentElementId attribute value is element's ID."

This being said, I believe all parts of the proposal fit the use case and would be a good solution.

**Comment by Sevitas** [comment]
We found some issues with proposed solution. 
MAPI SDK maps elements on element id [https://github.com/kontent-ai/management-sdk-net/blob/a94d1601fc2baa7aa43b5dcffc1bf835085bf01a/Kontent.Ai.Management/Modules/ModelBuilders/ElementModelProvider.cs#L21](https://github.com/kontent-ai/management-sdk-net/blob/a94d1601fc2baa7aa43b5dcffc1bf835085bf01a/Kontent.Ai.Management/Modules/ModelBuilders/ElementModelProvider.cs#L21). We need to change this to include codename and external id as well before we release [this feature](https://github.com/kontent-ai/model-generator-net/issues/167).

**Comment by Sevitas** [comment]
After further discussion, we have decided not to continue with this effort. For the complete reasoning please see https://github.com/kontent-ai/management-sdk-net/issues/210.
