### ISSUE TITLE
IEnumerable<object> Generated for known types

### ISSUE THREAD

**Issue by xantari** [kontent-ai/model-generator-net#90]
### Motivation

When generating a class for a known content type that has embedded content types they get generated with incorrect types of "object" instead of the strongly typed class. Additionally, when a constraint is "Exactly 1", the object still gets generated as an IEnumerable (implying more than 1).

Here is an example:
![image](https://user-images.githubusercontent.com/6610039/68712979-6fde6080-0562-11ea-9dbc-490055fab34b.png)

This got generated as follows:

```cs
public IEnumerable<object> NavigationTemplate { get; set; }
```

It should be expected that this get generated as this:

```cs
public NavigationTemplate NavigationTemplate { get; set; }
```

### Proposed solution

Ideally the .NET code generator could differentiate between Exactly 1 and other values, and more importantly be bound to the correct type.

At a minimum it should have been able to figure out that it should have been an IEnumerable&lt;NavigationType&gt; instead of IEnumerable&lt;object&gt;

**Comment by petrsvihlik** [comment]
Hi @xantari , thank you for reporting the issue! We actually know about it. It has already been reported in #17 

The best practice, for now, is: https://github.com/Kentico/kontent-generators-net/blob/master/README.md#handling-content-element-constraints

I'll close the other issue and leave this one open as it's better described.

**Comment by petrsvihlik** [comment]
Temporarily, we could allow specifying the Management API key (optionally) and retrieving the `item_count_limit` and `allowed_content_types` from the `/{project_id}/types/` endpoint as described at https://docs.kontent.ai/reference/management-api-v2#section/Linked-items-element-in-type.

Logic to apply:
- if `item_count_limit == 1` 
  - and `sum(allowed_content_types) > 1 or undefined` => `object`
  - and `sum(allowed_content_types) == 1 (e.g. Article)` => `Article`
- if `item_count_limit > 1` and `sum(allowed_content_types) == 1 (e.g. Article)` => `IEnumerable<Article>`
- all other cases => `IEnumerable<object>`

Similarly, we could generate more specific types for collections of Assets using the `asset_count_limit`.

**Comment by Simply007** [comment]
One approach would be #148 

My approach might lead to clearer separation of the generated output: 
I have a slightly different idea to be able to serve sam models for Production and preview API as well.

Still generate the base models as this (or currently `object` instead of `ContentItem`):

Article.Generated.cs

```
// multiple items of same type
public IEnumerable<ContentItem> Topics { get; set; }
// single item on one type
public IEnumerable<ContentItem> Hero { get; set; }
// multiple items of multiple types (i.e. BannerSection, HeroSection)
public IEnumerable<ContentItem> Sections { get; set; }
```

An of some parameter (i.e. -e) is applied you get 


Article.Typed.Generated.cs

```
public IEnumerable<Topic> TopicsTyped => Topic.OfType<Topic>();
public Hero HeroSingle => Hero.OfType<Hero>().FirstOrDefault();

// not sure whether this but it is possible
// because of you have 20 properties you you'd end up with 20 properties
// And for these you might want to use 
public IEnumerable<Banner>  Sections.OfType<Banner>();
````

**Comment by Simply007** [comment]
We should mind https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-DataAnnotations-attributes

We should mind these practices: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Partial-class-customization-techniques

We should mind multiple mapping logic: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models#naming-the-properties

**Comment by Sevitas** [comment]
After further discussions we have came up with the following RFP:

- every model will implement _IContentItem_ interface containg system property `public IContentItemSystemAttributes System { get; set; }`
  - Linked items will be as well of type `IEnumerable<IContentItem>`
  - Naming? is IContnentItem safe to use? Is there a better name?
- typed model properties will be separated to their own files
  - eg. type _Article_ will generate files _Article.cs, Article.Generated.cs, Article.Typed.Generated.cs_
  - Naming? Can we use _typed_ in the name of the file?
- typed models will cover up 4 scenarios

### Scenario 1
Linked items element limited to a single type with at least 1 item.
Article.Generated.cs will contain
```csharp
public IEnumerable<ContentItem> Topics { get; set; }
```
Article.Typed.Generated.cs will contain
```csharp
public IEnumerable<Topic> TopicsTyped => Topic.OfType<Topic>();
```

### Scenario 2
Linked items element limited to a single type with at most or exactly 1 item.
Article.Generated.cs will contain
```csharp
public IEnumerable<ContentItem> Header { get; set; }
```
Article.Typed.Generated.cs will contain
```csharp
public Header HeaderSingle => Header.OfType<Header>().FirstOrDefault();
```

### Scenario 3
Linked items element limited to a multiple types with at least 1 at most or exactly 1 item. 
Article.Generated.cs will contain
```csharp
public IEnumerable<ContentItem> Attachement { get; set; }
```
Article.Typed.Generated.cs will contain
```csharp
public Image AttachementImageSingle => Attachement.OfType<Image>().FirstOrDefault();
public Other AttachementOtherSingle => Attachement.OfType<Other>().FirstOrDefault();
```
As a developer you still need to check which property contains a value. Other properties will contain a null.

### Scenario 4
Linked items element limited to a multiple types with at least 1 item.
Article.Generated.cs will contain
```csharp
public IEnumerable<ContentItem> Sections { get; set; }
```
Article.Typed.Generated.cs will contain
```csharp
public IEnumerable<Banner> BannerSectionTyped => Sections.OfType<Banner>();
public IEnumerable<CompanyNews> CompanyNewsSectionTyped => Sections.OfType<CompanyNews>();
```
As a developer you still need to check which properties contains any items. Some properties might be empty.

### Notes
1. [DataAnnotations](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-DataAnnotations-attributes)
  a. annotations should work as expected
3. [Customizations](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Partial-class-customization-techniques)
  a. customization should work as expected
  b. If we have decided to use class instead of interface _IContentItem_, customization with a class would not be possible
4. [Naming](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models#naming-the-properties)
  a. we should make sure name of the interface _IContentItem_ is reserved keyword
5. You can try to generate models for your own project using the [branch](https://github.com/Kentico/kontent-generators-net/tree/feature/90_generate_known_types_typed_1_2_3_4). Be aware that it is still a work in progress.

### Questions
1. Does the naming of the typed properties make sense?
6. Does these scenarios make sense?

**Comment by mcbeev** [comment]
I think I understand it pretty well. 

1. Yes, the naming to me makes sense. 
2. I can't say that I run into that many issues with the current model (of "object"), but overall I think this would be helpful and eliminate extra (somewhat redundant calls) to learn more about linked items. I like the ability to still generate the old way if needed. I would be for this approach.

**Comment by mattnield** [comment]
I'd agree, makes sense. I've not run into this too much as an issue myself, but I can see how it's going to add clarity. I think for `IEnumerable<object>` vs. `IEnumerable<IContentItem>` that I'd rather choose between the two that have them both.

**Comment by mcbeev** [comment]
@Simply007 

1. As long as it it is optional or configurable (so the old way still works) I'm ok with it. 
2. I could potentially see scenario 3 making scenario 2 not needed.

**Comment by frederikstonge** [comment]
Scenario 4 won't work for us because we want to keep the order of each items. 

I think it is a nice idea to change "object" to "IContentItem" that includes IContentItemSystemAttributes. I had to use the base class options and change the class to an interface.

I don't know if generating the typed items is a good Idea, I prefer to do it manually for my needs.

**Comment by Enngage** [comment]
Naming conventions are ok, as well as `IContentItem` interface :) 

Scenario 1 is nice to have. 

Scenario 2 could be tricky to implement as Delivery SDK doesn't have the prior knowledge of how many items there can be and for the mapping we might need to use reflection on the model to see if there is a property with that given name and if it's enumerable or not. 

Scenario 3 & 4 are quite dangerous as if types are omitted or many types are available it could easily generate hundreds of properties in a single content type model. Not sure if we want to potentially create such large type models.

**Comment by Sevitas** [comment]
After further discussions we have decided to implement scenarios 1, 2. The other scenarios will be solved in [scenario 3](https://github.com/kontent-ai/model-generator-net/issues/160) and [scenario 4](https://github.com/kontent-ai/model-generator-net/issues/161).

**Comment by KevinByrd-28** [comment]
Hello everyone.  I would just like to push this issue to the forefront again as I am facing this problem as well.  It's becoming an increasingly heavy nuisance when I run the model generator and I then have to go back through models to change the "Object" to an explicit content model for intellisense.  Seems like the MG should either avoid the use of object tags all together or not overwrite edits made to the content model.

**Comment by frederikstonge** [comment]
> Hello everyone. I would just like to push this issue to the forefront again as I am facing this problem as well. It's becoming an increasingly heavy nuisance when I run the model generator and I then have to go back through models to change the "Object" to an explicit content model for intellisense. Seems like the MG should either avoid the use of object tags all together or not overwrite edits made to the content model.

Actually, you shouldn't modify the .Generated file. You should create new Property in the normal file (which is not overriden) and add properties that access the Generated one with proper "cast".

Exemple :
```cs
Item.Generated.cs

public partial class Item
{
    public const string Codename = "item";
    public const string ComponentsCodename = "components";

    public IEnumerable<object> Components { get; set; }
    public IContentItemSystemAttributes System { get; set; }
}
```
```cs
Item.cs

public partial class Item
{
    public IEnumerable<Type> ComponentsValue => Components?.OfType<Type>();
}
```

**Comment by KevinByrd-28** [comment]
> 

Thank you for that, that should be helpful

**Comment by Sevitas** [comment]
Hi @KevinByrd-28, 
I can confirm @frederikstonge's answer is correct. The generated files contain documentation comments containing information about the modification of the files.

**Comment by Simply007** [comment]
Waiting for https://github.com/kontent-ai/management-sdk-net/issues/197.
